

= Text.Combine(
    List.Select(
        Text.Split(Text.FromBinary([Content]), "#(lf)"),
        each Text.Contains(_, "error", Comparer.OrdinalIgnoreCase)
    ),
    "#(lf)"
)





= Text.Combine(
    List.Select(
        Text.Split(Text.FromBinary([Content]), "#(lf)"),
        each 
            Text.Contains(_, "error", Comparer.OrdinalIgnoreCase) 
            and not Text.Contains(_, "FieldConversionError", Comparer.OrdinalIgnoreCase)
    ),
    "#(lf)"
)


= Text.Combine(
    List.Select(
        Text.Split(Text.FromBinary([Content]), "#(lf)"),
        each 
            Text.Contains(_, "error", Comparer.OrdinalIgnoreCase) 
            and not Text.Contains(_, "FieldConversionError", Comparer.OrdinalIgnoreCase)
            and not Text.Contains(_, "warning", Comparer.OrdinalIgnoreCase)
    ),
    "#(lf)"
)




= try 
    Text.Select(
        List.First(
            List.Select(
                Text.Split([Subject], " "), 
                each Text.Contains(_, "IN_") or Text.Contains(_, "ID_")
            )
        ), 
        {"A".."Z", "a".."z", "0".."9", "_"}
    ) 
otherwise null




= if Text.Contains([Subject], "IN_") then "IN" 
  else if Text.Contains([Subject], "ID_") then "ID" 
  else null




let 
    errorText = [Error],
    jobName = [Job Name],
    toolIdFound = 
        if errorText <> null and Text.Contains(errorText, "ToolId") then
            let
                afterToolId = Text.AfterDelimiter(errorText, "ToolId "),
                extractedId = Text.BeforeDelimiter(afterToolId, ":")
            in
                "ToolId " & Text.Trim(extractedId)
        else
            null,
    toolRecord = 
        if toolIdFound <> null then
            let 
                filteredTool = Table.SelectRows(TOOL_LIST, each [Job Name] = jobName and [Tool ID] = toolIdFound)
            in 
                if Table.RowCount(filteredTool) > 0 then 
                    filteredTool{0}[Tool Name]
                else 
                    null
        else
            null,
    updatedError = 
        if toolIdFound <> null and toolRecord <> null then
            Text.Replace(errorText, toolIdFound, toolIdFound & " (Tool Name- " & toolRecord & ")")
        else
            errorText
in
    updatedError








let 
    errorText = [Error],
    jobName = [Job Name],
    toolIdFound = 
        if errorText <> null and Text.Contains(errorText, "ToolId") then
            let
                afterToolId = Text.AfterDelimiter(errorText, "ToolId "),
                extractedId = Text.BeforeDelimiter(afterToolId, ":")
            in
                "ToolId " & Text.Trim(extractedId)
        else
            null,
    toolRecord = 
        if toolIdFound <> null then
            let 
                filteredTool = Table.SelectRows(Tool_List, each [Job Name] = jobName and [Tool ID] = toolIdFound)
            in 
                if Table.RowCount(filteredTool) > 0 then 
                    filteredTool{0}[Tool Name]
                else 
                    null
        else
            null,
    updatedError = 
        if toolIdFound <> null and toolRecord <> null then
            Text.Replace(errorText, toolIdFound, toolIdFound & " (Tool Name- " & toolRecord & ")")
        else
            errorText
in
    updatedError







let 
    errorText = [Error],
    jobName = [Job Name],
    toolIdsFound = 
        if errorText <> null and Text.Contains(errorText, "ToolId") then
            List.Transform(
                Text.Split(errorText, "ToolId "),
                each Text.BeforeDelimiter(_, ":")
            )
        else
            {},
    toolIdsCleaned = 
        List.Select(
            List.Transform(toolIdsFound, each Text.Trim(_)),
            each _ <> ""
        ),
    updatedError = 
        List.Accumulate(
            toolIdsCleaned, 
            errorText, 
            (state, currentToolId) =>
                let
                    toolIdFull = "ToolId " & currentToolId,
                    toolRecord = 
                        let 
                            filteredTool = Table.SelectRows(Tool_List, each [Job Name] = jobName and [Tool ID] = toolIdFull)
                        in 
                            if Table.RowCount(filteredTool) > 0 then 
                                filteredTool{0}[Tool Name]
                            else 
                                null,
                    newToolIdText = 
                        if toolRecord <> null then 
                            toolIdFull & " (Tool Name- " & toolRecord & ")" 
                        else 
                            toolIdFull
                in
                    Text.Replace(state, toolIdFull, newToolIdText)
        )
in
    updatedError





